version: '3.9'

services:
  mongodb:
    container_name: MongoDB
    image: mongo:6.0
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ReX\8-
    volumes:
      - ./mongo-data:/data/db
  
  mongo-express:
    container_name: Mongo-Express
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ReX\8-
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017